name: Pull Request CI

on: [pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to comment on PRs
      contents: read # Required to checkout code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet build 10xVibeTravels/10xVibeTravels.csproj --configuration Release

      - name: Run unit tests with coverage
        run: dotnet test 10VibeTravels.Tests/10VibeTravels.Tests.csproj --configuration Release --collect:"XPlat Code Coverage"

      - name: Post PR Comment
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '''✅ Kompilacja i testy zakończone pomyślnie! Zebrano informacje o pokryciu kodu.'''
            }); 